services:

  postgres-product:
    container_name: postgres-product
    image: postgres:15.4
    environment:
      POSTGRES_USER: admin-product
      POSTGRES_PASSWORD: admin-product
      PGDATA: /data/postgres
    volumes:
      - postgres-product:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  postgres-basket:
    container_name: postgres-basket
    image: postgres:15.4
    environment:
      POSTGRES_USER: admin-basket
      POSTGRES_PASSWORD: admin-basket
      PGDATA: /data/postgres
      PGPORT: 5433
    volumes:
      - postgres-basket:/data/postgres
    ports:
      - "5433:5433"
    networks:
      - postgres
    restart: unless-stopped

  postgres-keycloak:
    container_name: postgres-keycloak
    image: postgres:15.4
    environment:
      POSTGRES_USER: admin-keycloak
      POSTGRES_PASSWORD: admin-password
      PGDATA: /data/postgres
      PGPORT: 5434
      POSTGRES_DB: keycloak
    volumes:
      - postgres-keycloak:/data/postgres
    ports:
      - "5434:5434"
    networks:
      - postgres
    restart: unless-stopped

  postgres-user:
    container_name: postgres-user
    image: postgres
    environment:
      POSTGRES_USER: admin-user
      POSTGRES_PASSWORD: admin-user
      PGDATA: /data/postgres
      PGPORT: 5435
    volumes:
      - postgres-user:/data/postgres
    ports:
      - "5435:5435"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.1
    command: [ "start-dev" ]
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak
      DB_USER: admin-keycloak
      DB_PASSWORD: admin-keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realms:/opt/keycloak/data/import/
    ports:
      - "8181:8080"
    depends_on:
      - postgres-keycloak

networks:
  postgres:
    driver: bridge

volumes:
  postgres-product:
  postgres-basket:
  postgres-keycloak:
  postgres-user:
  pgadmin:
