server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
          - Path=/products/**
          filters:
          - RewritePath=/products/(?<path>.*), /$\{path}

        - id: basket-service
          uri: lb://basket-service
          predicates:
          - Path=/baskets/**
          filters:
          - RewritePath=/baskets/(?<path>.*), /$\{path}

        - id: openapi
          uri: http://localhost:8080
          predicates:
          - Path=/v3/api-docs/**
          filters:
          - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

        - id: user-service
          uri: lb://user-service
          predicates:
          - Path=/users/**
          filters:
            - RewritePath=/users/(?<path>.*), /$\{path}

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    urls:
      - name: products
        url: /v3/api-docs/products
      - name: baskets
        url: /v3/api-docs/baskets
      - name: users
        url: /v3/api-docs/users