server:
  port: 0
  forward-headers-strategy: framework

spring:
  application:
    name: product-service

  datasource:
    username: 'admin-product'
    password: 'admin-product'
    url: jdbc:postgresql://localhost:5432/product

  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true


