server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: product-service

  datasource:
    username: 'admin'
    password: 'admin'
    url: jdbc:postgresql://postgres:5432/product

  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/marketplace-app-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  liquibase:
    change-log: changelog.xml
    enabled: true

  kafka:
    bootstrap-servers: "broker:29092"

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

jwt:
  auth:
    converter:
      principle-attribute: "preferred_username"
      resource-id: "marketplace-app"
