server:
  port: 8083
  forward-headers-strategy: framework

spring:
  application:
    name: basket-service

  datasource:
    username: 'admin'
    password: 'admin'
    url: jdbc:postgresql://postgres:5432/basket

  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/marketplace-app-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  main:
    allow-bean-definition-overriding: true

  kafka:
    bootstrap-servers: "broker:29092"

  liquibase:
    change-log: changelog.xml
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
    enabled: false

jwt:
  auth:
    converter:
      principle-attribute: "preferred_username"
      resource-id: "marketplace-app"

feign:
  product:
    url: product-service