spring:
  application:
    name: basket-service

  datasource:
    username: 'admin-basket'
    password: 'admin-basket'
    url: jdbc:postgresql://localhost:5433/basket

  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 0
  forward-headers-strategy: framework